spring:
  application:
    name: psycho-logger

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 90MB
      max-request-size: 90MB

server:
  port: 8080

backup:
  mysqldump:
    path: mysqldump
  mysql:
    path: mysql

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never